name: golangci-lint

on:
  push:
    branches: [ main, dev, feat/* ]
  pull_request:
    branches: [ main, dev, feat/* ]

permissions:
  contents: read

jobs:
  golangci:
    name: golangci linter
    runs-on: ubuntu-latest
    env:
      FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: 1.23.6
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v6
        with:
          version: v2.11.4
          args: --timeout 10m0s --max-issues-per-linter 0 --max-same-issues 0 --print-issued-lines
          only-new-issues: true
